{ lib }:
let
  sources = [
    ../lib/mk-tests.nix
    ../lib/terminal/expect.nix
    ../lib/terminal/locators.nix
    ../lib/terminal/terminal.nix
    ../lib/vm/actions.nix
    ../lib/vm/expect.nix
    ../lib/workspace.nix
    ../overlay.nix
  ];

  trimIndent = body:
    let
      lines = lib.splitString "\n" body;
      first = lib.findFirst (line: line != "") "" lines;
      match = builtins.match "^( +).*" first;
      indent = if match == null then "" else builtins.head match;
      strip = line:
        if lib.hasPrefix indent line then
          builtins.substring (builtins.stringLength indent) (-1) line
        else
          line;
    in
    lib.trim (lib.concatMapStringsSep "\n" strip lines);

  parse = source:
    let
      parts = builtins.split "/\\*\\*[[:space:]]*@doc[[:space:]]+([^[:space:]]+)\n" (
        builtins.readFile source
      );
      consume = rest:
        if builtins.length rest < 2 then
          [ ]
        else
          let
            capture = builtins.elemAt rest 0;
            following = builtins.elemAt rest 1;
            body = builtins.head (builtins.split "\\*/" following);
          in
          [
            {
              name = builtins.head capture;
              text = trimIndent body;
            }
          ]
          ++ consume (lib.drop 2 rest);
    in
    consume (lib.drop 1 parts);

  entries = lib.sort (a: b: a.name < b.name) (lib.concatMap parse sources);
  names = map (entry: entry.name) entries;
  uniqueNames = lib.unique names;
  sections = map (entry: entry.text) entries;
in
assert lib.assertMsg (entries != [ ]) "No @doc entries found";
assert lib.assertMsg (
  builtins.length names == builtins.length uniqueNames
) "Duplicate @doc entries found";
''
  <!-- Generated by docs/generate-api.nix. Do not edit. -->

  # API Reference

  This reference is generated from documentation beside the public Nix API.
  Edit the corresponding `@doc` block and regenerate this page instead of
  editing it directly.

  ${lib.concatStringsSep "\n\n---\n\n" sections}
''
