{ lib }:
let
  sources = [
    ../core/mk-tests.nix
    ../core/builders.nix
    ../module.nix
    ../terminal/matchers.nix
    ../terminal/locators.nix
    ../terminal/fixture.nix
    ../machine/fixture.nix
    ../machine/locators.nix
    ../machine/matchers.nix
    ../workspace/fixture.nix
  ];

  trimIndent = body:
    let
      lines = lib.splitString "\n" body;
      first = lib.findFirst (line: line != "") "" lines;
      match = builtins.match "^( +).*" first;
      indent = if match == null then "" else builtins.head match;
      strip = line:
        if lib.hasPrefix indent line then
          builtins.substring (builtins.stringLength indent) (-1) line
        else
          line;
    in
    lib.trim (lib.concatMapStringsSep "\n" strip lines);

  parse = source:
    let
      parts = builtins.split "/\\*\\*[[:space:]]*@doc[[:space:]]+([^[:space:]]+)\n" (
        builtins.readFile source
      );
      consume = rest:
        if builtins.length rest < 2 then
          [ ]
        else
          let
            capture = builtins.elemAt rest 0;
            following = builtins.elemAt rest 1;
            body = builtins.head (builtins.split "\\*/" following);
          in
          [
            {
              name = builtins.head capture;
              text = trimIndent body;
            }
          ]
          ++ consume (lib.drop 2 rest);
    in
    consume (lib.drop 1 parts);

  entries = lib.sort (a: b: a.name < b.name) (lib.concatMap parse sources);
  names = map (entry: entry.name) entries;
  uniqueNames = lib.unique names;
  categories = {
    core = entry:
      entry.name == "test"
      || entry.name == "test.configure"
      || lib.hasPrefix "testing." entry.name
      || lib.hasPrefix "lib." entry.name;
    terminal = entry:
      entry.name == "expect.terminal"
      || lib.hasPrefix "terminal." entry.name
      || lib.hasPrefix "workspace." entry.name;
    machine = entry:
      entry.name == "expect.machine"
      || lib.hasPrefix "machine." entry.name;
  };
  render = title: selected: ''
    <!-- Generated by docs/generate-api.nix. Do not edit. -->

    # ${title}

    This reference is generated from documentation beside the public Nix API.
    Edit the corresponding `@doc` block and regenerate this page instead of
    editing it directly.

    ${lib.concatStringsSep "\n\n---\n\n" (map (entry: entry.text) selected)}
  '';
  categorized = lib.concatMap (entry: lib.optional (lib.any (select: select entry) (builtins.attrValues categories)) entry) entries;
in
assert lib.assertMsg (entries != [ ]) "No @doc entries found";
assert lib.assertMsg (
  builtins.length names == builtins.length uniqueNames
) "Duplicate @doc entries found";
assert lib.assertMsg (
  builtins.length categorized == builtins.length entries
) "Uncategorized @doc entries found";
{
  core = render "Core API" (builtins.filter categories.core entries);
  terminal = render "Terminal API" (builtins.filter categories.terminal entries);
  machine = render "Machine API" (builtins.filter categories.machine entries);
}
