{ lib }:
let
  sources = [
    ../flake.nix
    ../overlay.nix
    ../core/github-matrix.nix
    ../core/mk-tests.nix
    ../core/builders.nix
    ../module.nix
    ../terminal/matchers.nix
    ../terminal/locators.nix
    ../terminal/fixture.nix
    ../machine/fixture.nix
    ../machine/locators.nix
    ../machine/matchers.nix
    ../expect/fixture.nix
    ../browser/fixture.nix
    ../browser/matchers.nix
    ../container/fixture.nix
    ../container/matchers.nix
    ../desktop/fixture.nix
    ../desktop/matchers.nix
    ../filesystem/fixture.nix
    ../filesystem/matchers.nix
    ../http/fixture.nix
    ../http/matchers.nix
    ../network/fixture.nix
    ../network/matchers.nix
    ../result/fixture.nix
    ../result/matchers.nix
    ../service/fixture.nix
    ../service/matchers.nix
    ../step/fixture.nix
    ../user/fixture.nix
    ../user/matchers.nix
  ];

  trimIndent =
    body:
    let
      lines = lib.splitString "\n" body;
      first = lib.findFirst (line: line != "") "" lines;
      match = builtins.match "^( +).*" first;
      indent = if match == null then "" else builtins.head match;
      strip =
        line:
        if lib.hasPrefix indent line then
          builtins.substring (builtins.stringLength indent) (-1) line
        else
          line;
    in
    lib.trim (lib.concatMapStringsSep "\n" strip lines);

  parse =
    source:
    let
      parts = builtins.split "/\\*\\*[[:space:]]*@doc[[:space:]]+([^[:space:]]+)\n" (
        builtins.readFile source
      );
      consume =
        rest:
        if builtins.length rest < 2 then
          [ ]
        else
          let
            capture = builtins.elemAt rest 0;
            following = builtins.elemAt rest 1;
            body = builtins.head (builtins.split "\\*/" following);
          in
          [
            {
              name = builtins.head capture;
              text = trimIndent body;
            }
          ]
          ++ consume (lib.drop 2 rest);
    in
    consume (lib.drop 1 parts);

  entries = lib.sort (a: b: a.name < b.name) (lib.concatMap parse sources);
  names = map (entry: entry.name) entries;
  uniqueNames = lib.unique names;
  categories = {
    core =
      entry:
      entry.name == "test"
      || lib.hasPrefix "test." entry.name
      || lib.hasPrefix "testing." entry.name
      || lib.hasPrefix "lib." entry.name
      || lib.hasPrefix "testers." entry.name;
    terminal =
      entry:
      entry.name == "expect.terminal-machine"
      || lib.hasPrefix "terminal." entry.name
      || lib.hasPrefix "terminal-machine." entry.name
      || entry.name == "expect.machine-command"
      || lib.hasPrefix "machine." entry.name;
    fixtures = entry: lib.hasPrefix "fixture." entry.name;
    assertions =
      entry:
      lib.hasPrefix "assertions." entry.name
      || entry.name == "expect.terminal-machine"
      || entry.name == "expect.machine-command";
  };
  render = title: selected: ''
    <!-- Generated by docs/generate-api.nix. Do not edit. -->

    # ${title}

    ${lib.concatStringsSep "\n\n---\n\n" (map (entry: entry.text) selected)}
  '';
  categorized = lib.concatMap (
    entry: lib.optional (lib.any (select: select entry) (builtins.attrValues categories)) entry
  ) entries;
  terminalEntries =
    builtins.filter (
      entry: entry.name == "expect.terminal-machine" || lib.hasPrefix "terminal-machine." entry.name
    ) entries
    ++ builtins.filter (
      entry: entry.name == "expect.machine-command" || lib.hasPrefix "machine." entry.name
    ) entries
    ;
  assertionEntries = builtins.filter categories.assertions entries;
in
assert lib.assertMsg (entries != [ ]) "No @doc entries found";
assert lib.assertMsg (
  builtins.length names == builtins.length uniqueNames
) "Duplicate @doc entries found";
assert lib.assertMsg (
  builtins.length categorized == builtins.length entries
) "Uncategorized @doc entries found";
{
  core = render "Core API" (builtins.filter categories.core entries);
  terminal = render "Terminal and Machine API" terminalEntries;
  fixtures = render "Fixture API" (builtins.filter categories.fixtures entries);
  assertions = render "Assertion API" assertionEntries;
}
